# Generated by Django 5.2 on 2026-04-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listening',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='reading',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='speaking',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='writing',
            field=models.IntegerField(default=1),
        ),
    ]
