# Generated by Django 5.1.7 on 2026-04-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='meeting_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
