# Generated by Django 5.1.7 on 2026-04-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_meeting_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newword',
            name='status',
            field=models.CharField(blank=True, choices=[('hard', 'Difícil (Não lembrei)'), ('medium', 'Médio (Mais ou menos)'), ('easy', 'Fácil (Lembrei)')], max_length=10, null=True),
        ),
    ]
