# Generated by Django 5.1.7 on 2026-04-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_newword_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('rescheduled', 'Rescheduled'), ('missed', 'Missed')], default='scheduled', max_length=20),
        ),
    ]
