# Generated by Django 6.0.4 on 2026-04-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lesson_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='level',
            field=models.CharField(choices=[('A1/A2', 'A1 / A2'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=10),
        ),
        migrations.AlterField(
            model_name='newword',
            name='level',
            field=models.CharField(choices=[('A1/A2', 'A1 / A2'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=10),
        ),
    ]
