# Generated by Django 5.2 on 2026-04-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_lesson_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('rescheduled', 'Rescheduled'), ('missed', 'Missed')], default='scheduled', max_length=20),
        ),
    ]
