# Generated by Django 5.2 on 2026-05-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_studentrecurringschedule_lesson_template_and_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newword',
            name='level',
            field=models.CharField(choices=[('A1/A2', 'A1 / A2'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('ALL LEVELS', 'All Levels')], max_length=10),
        ),
    ]
