# Generated by Django 5.2 on 2026-05-11 21:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_default_categories(apps, schema_editor):
    VocabularyCategory = apps.get_model('lessons', 'VocabularyCategory')
    for slug, name in [
        ('grammar', 'Grammar'),
        ('vocabulary', 'Vocabulary'),
        ('expressions', 'Expressions'),
        ('phrasal-verbs', 'Phrasal Verbs'),
        ('pronunciation', 'Pronunciation'),
        ('business-english', 'Business English'),
    ]:
        VocabularyCategory.objects.get_or_create(
            owner=None,
            slug=slug,
            defaults={'name': name, 'is_default': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_homework_homeworkquestion_homeworktemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('lesson', 'Lesson')], default='student', max_length=20)),
                ('word', models.CharField(max_length=255)),
                ('translation', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('example_sentence', models.TextField(blank=True)),
                ('pronunciation', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('custom_category', models.CharField(blank=True, max_length=120)),
                ('audio', models.FileField(blank=True, null=True, upload_to='vocabulary/audio/')),
                ('audio_url', models.URLField(blank=True)),
                ('favorite', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('mastered', models.BooleanField(default=False)),
                ('easiness_factor', models.FloatField(default=2.5)),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('repetition_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('confidence_level', models.PositiveSmallIntegerField(default=0)),
                ('difficulty_level', models.CharField(choices=[('new', 'New'), ('weak', 'Weak'), ('learning', 'Learning'), ('stable', 'Stable'), ('mastered', 'Mastered')], default='new', max_length=20)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocabulary_cards', to='lessons.lesson')),
                ('source_new_word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocabulary_cards', to='lessons.newword')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_cards', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocabulary_cards_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='lessons.vocabularycategory')),
            ],
            options={
                'ordering': ['next_review_at', '-failure_count', 'word'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyReviewLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[('very_hard', 'Muito Dificil'), ('hard', 'Dificil'), ('easy', 'Facil')], max_length=20)),
                ('review_quality', models.PositiveSmallIntegerField()),
                ('previous_easiness_factor', models.FloatField()),
                ('new_easiness_factor', models.FloatField()),
                ('previous_interval_days', models.PositiveIntegerField()),
                ('new_interval_days', models.PositiveIntegerField()),
                ('previous_repetition_count', models.PositiveIntegerField()),
                ('new_repetition_count', models.PositiveIntegerField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('next_review_at', models.DateTimeField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='lessons.vocabularycard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_review_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyReviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cards_reviewed', models.PositiveIntegerField(default=0)),
                ('easy_count', models.PositiveIntegerField(default=0)),
                ('hard_count', models.PositiveIntegerField(default=0)),
                ('very_hard_count', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_review_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vocabularycategory',
            index=models.Index(fields=['owner', 'slug'], name='lessons_voc_owner_i_de9759_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularycategory',
            index=models.Index(fields=['is_default', 'slug'], name='lessons_voc_is_defa_e6d381_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vocabularycategory',
            unique_together={('owner', 'slug')},
        ),
        migrations.AddIndex(
            model_name='vocabularycard',
            index=models.Index(fields=['student', 'archived', 'next_review_at'], name='lessons_voc_student_b08b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularycard',
            index=models.Index(fields=['student', 'difficulty_level', 'archived'], name='lessons_voc_student_1dcd80_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularycard',
            index=models.Index(fields=['student', 'mastered', 'archived'], name='lessons_voc_student_037bc0_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularycard',
            index=models.Index(fields=['teacher', 'created_at'], name='lessons_voc_teacher_691c64_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularyreviewlog',
            index=models.Index(fields=['student', 'reviewed_at'], name='lessons_voc_student_a834b8_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularyreviewlog',
            index=models.Index(fields=['card', 'reviewed_at'], name='lessons_voc_card_id_67481b_idx'),
        ),
        migrations.RunPython(create_default_categories, migrations.RunPython.noop),
    ]
