# Generated by Django 6.0.4 on 2026-06-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_lesson_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkquestion',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='homework/questions/audio/'),
        ),
        migrations.AddField(
            model_name='homeworkquestion',
            name='audio_transcript',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homeworkquestion',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='homework/questions/images/'),
        ),
    ]
