# Generated by Django 6.0.4 on 2026-08-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_homeworkquestion_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='auto_correction_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='report_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='student_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='homeworkanswer',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeworkanswer',
            name='auto_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homeworkanswer',
            name='auto_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homeworkanswer',
            name='correction_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='homeworkanswer',
            name='expected_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homeworkanswer',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeworkanswer',
            name='second_chance_answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeworkanswer',
            name='second_chance_answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeworkanswer',
            name='second_chance_expected_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homeworkanswer',
            name='second_chance_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homeworkanswer',
            name='second_chance_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homeworkanswer',
            name='second_chance_is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeworkanswer',
            name='second_chance_selected_option_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeworkquestion',
            name='correction_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homeworkquestion',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homeworkquestion',
            name='reference_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homeworkquestion',
            name='reserve_correct_option_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeworkquestion',
            name='reserve_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homeworkquestion',
            name='reserve_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='homeworkquestion',
            name='reserve_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homeworkquestion',
            name='reserve_reference_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homeworkquestion',
            name='reserve_type',
            field=models.CharField(blank=True, choices=[('open_text', 'Open text'), ('multiple_choice', 'Multiple choice')], default='open_text', max_length=20),
        ),
        migrations.AddField(
            model_name='homeworkquestion',
            name='second_chance_mode',
            field=models.CharField(choices=[('none', 'None'), ('ai_generated', 'AI generated'), ('reserve', 'Reserve question')], default='ai_generated', max_length=20),
        ),
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('sent', 'Sent'), ('corrected', 'Corrected')], default='draft', max_length=20),
        ),
    ]
