# Generated by Codex on 2026-09-14

from django.db import migrations, models


def mark_existing_reschedules_as_exceptions(apps, schema_editor):
    Lesson = apps.get_model('lessons', 'Lesson')
    Lesson.objects.filter(status='rescheduled').update(schedule_exception=True)


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0017_homework_auto_correction_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='schedule_exception',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='original_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_reschedules_as_exceptions, migrations.RunPython.noop),
    ]
