# Generated by Codex on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0018_lesson_schedule_exception'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_extra',
            field=models.BooleanField(default=False),
        ),
    ]
