# Generated by Django 5.2 on 2026-05-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_options_payment_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfinanceprofile',
            name='contract_file',
            field=models.FileField(blank=True, max_length=768, null=True, upload_to='finance/contracts/'),
        ),
    ]
