# Generated by Django 5.2 on 2026-04-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='mode',
            field=models.CharField(choices=[('listening', 'Listening'), ('speaking', 'Speaking'), ('writing', 'Writing'), ('reading', 'Reading')], max_length=20),
        ),
    ]
