# Generated by Django 5.2 on 2026-04-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_alter_practicesession_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='mode',
            field=models.CharField(choices=[('listening', 'Listening'), ('speaking', 'Speaking'), ('writing', 'Writing')], max_length=20),
        ),
    ]
