# Generated by Django 5.2 on 2026-06-01 14:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_study', '0001_initial'),
        ('lessons', '0015_lesson_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aistudysession',
            options={'ordering': ['-last_interaction_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='aistudysession',
            name='last_interaction_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aistudysession',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_study_sessions', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='aistudysession',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aistudysession',
            name='title_source',
            field=models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='auto', max_length=20),
        ),
    ]
