# Generated by Django 5.2 on 2026-06-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_study', '0003_practice_modes_and_writing_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconversationmessage',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('feedback', 'Feedback'), ('writing_feedback', 'Writing feedback')], default='text', max_length=20),
        ),
    ]
