# Generated by Django 6.0.4 on 2026-08-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_study', '0006_aistudysession_is_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aistudysession',
            options={'ordering': ['-is_pinned', '-last_interaction_at', '-created_at']},
        ),
    ]
